[package]
authors = ["Daniel García Moreno <danigm@wadobo.com>"]
name = "update"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.32.0"
failure = "0.1.5"
regex = "1.1.0"
reqwest = "0.9.8"
serde = "1.0.85"

[dependencies.serde_json]
features = ["preserve_order"]
version = "1.0.36"
